apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: aksstuff
spec:
  components:
    - name: myvm
      type: azvm
      properties:
        resource_group: "aks-lab-lacj01"
        vm_name: "myvm"
        subnet_name: "gateway_internal"
        vnet_name: "virtual-network"
        password: "Passw0rd"
        writeConnectionSecretToRef:
          name: azvm-conn
          namespace: vela-system
